# Generated by Django 6.0.4 on 2026-05-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_handled',
            field=models.BooleanField(default=False),
        ),
    ]
